
---
title: 'Modeling - KKBox EDA'
date: '`r Sys.Date()`'
output:
  html_document:
    number_sections: true
    fig_caption: true
    toc: true
    fig_width: 7
    fig_height: 4.5
    theme: cosmo
    highlight: tango
    code_folding: hide
---

## Load libraries and helper functions
```{r, message = FALSE}
# general visualisation
library(needs)
needs(dplyr,ggplot2,readr,h2o,data.table,tibble,tidyr)
```



## Load data
```{r warning=FALSE, results=FALSE}
datalist <- c(201702,201613,201612,201611,201610,201609)
for (i in 1:length(datalist)){
  temp <- read_csv(paste0('jiseung_',datalist[i],'.csv'))
  if (i==1){
    train_df <- temp
  }
  else{
    train_df <- train_df %>% bind_rows(temp)
  }
  
}

test_df <- read_csv('logs_test_df_201704.csv')

train_df$is_churn <- as.factor(train_df$is_churn)
test_df$is_churn <- as.factor(test_df$is_churn)

```


## 셋 구분
```{r}
# seed <- 1
# set.seed(seed)
# idx <- sample(1:nrow(train_df), size = nrow(train_df)*0.3)
# # 훈련 데이터
# train <- as.data.frame(train_df[idx,])
# train$is_churn<-as.factor(train$is_churn)

train_df <- train_df[,-1]
test_df <- test_df[,-1]

# 테스트 데이터
# val <- as.data.frame(train_df[!1:nrow(train_df) %in% idx,])
# val$is_churn<-as.factor(val$is_churn)
```


## H2O 클러스터
```{r}
h2o.init(nthreads = 8, max_mem_size = '16G')
train_df$is_churn<-as.factor(train_df$is_churn)
train_Hex<-as.h2o(train_df)

# val$is_churn<-as.factor(val$is_churn)
# val_Hex<-as.h2o(val)

test_df$is_churn <- c(rep(1,(nrow(test_df)+1)/2),rep(0,(nrow(test_df)-1)/2))
test_df$is_churn <- as.factor(test_df$is_churn)
test_Hex<-as.h2o(test_df)
```

## Modeling
```{r}
predictors <- setdiff(names(train_Hex),
                       c("is_churn", "msno"))
response <- "is_churn"
```

```{r}
#--------------------------------------------------------------------------
# 4.2. GBM 정말 운좋은 모형 개발
#--------------------------------------------------------------------------
gbm_test_1 <- h2o.gbm(
  ## 표준 모형 모수 설정
  x = predictors, 
  y = response, 
  training_frame = train_Hex,
  nfolds=2,
  
  ntrees = 1000,                                                            
  
  learn_rate=0.001,                                                         

  stopping_rounds = 5, stopping_tolerance = 1e-4, stopping_metric = "logloss", 

  sample_rate = 0.8,                                                       
  col_sample_rate = 0.8,                                                   

  seed = 950902,                                                             
  score_tree_interval = 12                                                 
)

h2o.auc(h2o.performance(gbm_test_1, valid = FALSE))
```

```{r}
#--------------------------------------------------------------------------
# 4.3. GBM 모수 미세조정
#--------------------------------------------------------------------------
# hyper_params = list( max_depth = seq(1,29,2) )
hyper_params = list( max_depth = c(4,6,8,12,16,20) ) ## 빅데이터의 경우 사용

grid <- h2o.grid(

  hyper_params = hyper_params,
  search_criteria = list(strategy = "Cartesian"),

  algorithm="gbm",
  grid_id="depth_grid",
  
  x = predictors, 
  y = response, 
  training_frame = train_Hex,
  nfolds=2,
  

  ntrees = 10000,                                                            
  learn_rate = 0.05,                                                         
  learn_rate_annealing = 0.99,                                               
  
  sample_rate = 0.8,                                                       
  col_sample_rate = 0.8, 
  
  seed = 1234,                                                             
  
  stopping_rounds = 5,
  stopping_tolerance = 1e-4,
  stopping_metric = "AUC", 
  
  score_tree_interval = 10                                                
)

grid                                                                       

sortedGrid <- h2o.getGrid("depth_grid", sort_by="auc", decreasing = TRUE)    
sortedGrid


topDepths = sortedGrid@summary_table$max_depth[1:5]                       
minDepth = min(as.numeric(topDepths))
maxDepth = max(as.numeric(topDepths))
```

## gbm
```{r}
gbm <- h2o.gbm(x = predictors,
                      y = response,
                      training_frame = train_Hex,
                      # validation_frame = val_Hex,
                      nfolds=5,
                      ntree=500,
                      seed=950902)

pred_gbm <- h2o.predict(gbm,test_Hex)

test_df$gbm <- as.vector(pred_gbm$p1)

temp <- test_df %>% select(msno,gbm)
colnames(temp) <- c("msno","is_churn")
write.csv(temp,"gbm_only_201604.csv",row.names=FALSE)

gbm@model$variable_importances[1:20,]
```

## xgboost
```{r}
xgboost <- h2o.xgboost(x = predictors,
                      y = response,
                      training_frame = train_Hex,
                      # validation_frame = val_Hex,
                      ntree=200,
                      nfolds=3,
                      seed=950902)

pred_xgboost <- h2o.predict(xgboost,test_Hex)


test_df$xgboost <- as.vector(pred_xgboost$p1)

temp <- test_df %>% select(msno,xgboost)
colnames(temp) <- c("msno","is_churn")
write.csv(temp,"xgboost_only_201604.csv",row.names=FALSE)


xgboost@model$variable_importances[1:20,]
```

## rf
```{r}
rf <- h2o.randomForest(x = predictors,
                      y = response,
                      training_frame = train_Hex,
                      # validation_frame = val_Hex,
                      ntree=200,
                      nfolds=3,
                      seed=950902)


pred_rf <- h2o.predict(rf,test_Hex)

test_df$rf <- as.vector(pred_rf$p1)

temp <- test_df %>% select(msno,rf)
colnames(temp) <- c("msno","is_churn")
write.csv(temp,"rf_only_201604.csv",row.names=FALSE)

rf@model$variable_importances[1:20,]
```


```{r}
temp <- test_df %>% select(msno, xgboost, gbm, rf)
temp$is_churn <- temp %>% with((xgboost + gbm + rf)/3)
temp <- temp %>% select(msno, is_churn)
write.csv(temp,"total_only_201604.csv",row.names=FALSE)
```