---
title: 'User_user_log_pretreatment - KKBox EDA'
date: '`r Sys.Date()`'
output:
  html_document:
    number_sections: true
    fig_caption: true
    toc: true
    fig_width: 7
    fig_height: 4.5
    theme: cosmo
    highlight: tango
    code_folding: hide
---

## Load libraries and helper functions
```{r, message = FALSE}
# general visualisation
library(needs)
needs(tidyverse,scales,grid,gridExtra,RColorBrewer,corrplot,readr,
        data.table,tibble,tidyr,stringr,forcats,lubridate,ggforce,ggridges)
```

## Load data
```{r warning=FALSE, results=FALSE}
user_log <- read_csv('C:/Users/Owner/Rstudio/data/user_logs.csv')

user_log_v2 <- read_csv('C:/Users/Owner/Rstudio/data/user_logs_v2.csv')

user_log <- bind_rows(user_log,user_log_v2)
rm(user_log_v2);gc()

train_scala_labeled.csv
```

```{r}
# user_log$date<-gsub("-","",ymd(user_log$date)+30)

user_log_1 <- user_log %>% arrange(msno,date,total_secs)
user_log_1 <- user_log_1 %>% subset(!is.na(num_unq))
```

### 1.2017?? ???? log?? count(1??,2??,3??)
```{r}
temp <- user_log_1 %>% select(msno, date)
temp$date_ye_mo <- substr(temp$date,1,6)

temp <- temp %>%
  group_by(msno,date_ye_mo) %>%
  summarise(cnt=n())

temp <- temp %>% dcast(msno~date_ye_mo,value.var="cnt")

temp <- temp %>% select(msno,`201701`,`201702`,`201703`)
colnames(temp) <- c("msno","user_log_cnt_201701","user_log_cnt_201702","user_log_cnt_201703")
temp$user_log_cnt_201701 <- temp %>% with(ifelse(is.na(user_log_cnt_201701),0,user_log_cnt_201701))
temp$user_log_cnt_201702 <- temp %>% with(ifelse(is.na(user_log_cnt_201702),0,user_log_cnt_201702))
temp$user_log_cnt_201703 <- temp %>% with(ifelse(is.na(user_log_cnt_201703),0,user_log_cnt_201703))

col_01 <- temp
```

## Removing trash variables
```{r}
rm(temp)
rm(user_log_1);gc()
```

2. total_hours,total_num, rate_25, rate_50, rate_75, rate_100, rate_985
```{r}
user_log_1 <- user_log %>% arrange(msno,date,total_secs)
user_log_1 <- user_log_1 %>% subset(!is.na(num_unq))
user_log_1 <- user_log_1 %>% mutate(total_hours = round(total_secs/3600,2))
user_log_1 <- user_log_1 %>% mutate(total_num = num_25+num_50+num_75+num_100+num_985)
user_log_1 <- user_log_1 %>% mutate(rate_25 = round(num_25/total_num,2),
                            rate_50 = round(num_50/total_num,2),
                            rate_75 = round(num_75/total_num,2),
                            rate_100 = round(num_100/total_num,2),
                            rate_985 = round(num_985/total_num,2))
```

```{r}
user_log_2 <- user_log_1 %>% group_by(msno) %>% summarise(lst_date=max(date),
                                            log_count = n(), 
                                            mean_num_25 = mean(num_25),
                                            mean_num_50 = mean(num_50),
                                            mean_num_75 = mean(num_75),
                                            mean_num_985 = mean(num_985),
                                            mean_num_100 = mean(num_100),
                                            mean_total_secs = mean(total_secs),
                                            mean_rate_25 = mean(rate_25),
                                            mean_rate_50 = mean(rate_50),
                                            mean_rate_75 = mean(rate_75),
                                            mean_rate_985 = mean(rate_985),
                                            mean_rate_100 = mean(rate_100))
```

```{r}
user_log_2 <- user_log_2 %>% full_join(col_01,by="msno")
write.csv(user_log_2, file = "~/Desktop/r???͵?(??)/6_kaggle_competition/data/user_log_df_train_real.csv",row.names=FALSE)
```

## Removing trash variables
```{r}
# rm(user_log)
# rm(user_log_1)
# rm(user_log_2)
# rm(col_01)
```